name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Jika Anda pakai Vite/React, aktifkan baris di bawah ini dengan menghapus tanda '#'
      # - name: Install and Build
      #   run: npm install && npm run build

       Caviar - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: firebase deploy --only hosting --project reviews-1aeab --token "${{ secrets.FIREBASE_TOKEN }}"